### ISSUE TITLE
How do I add plugins?

### ISSUE THREAD

**Issue by BubblePlayzTHEREAL** [darverdevs/PluginInstallerRepo#8]
I have looked at readme.md and tried to make a pull request but it is not working. Anything I could do?

Here is the file I want to upload...
[skript.zip](https://github.com/darverdevs/PluginInstallerRepo/files/10158255/skript.zip)

**Comment by ColdDev** [comment]
With all due respect, please learn how to properly use Git & GitHub before trying to submit a pull request.
